# GitHub Pages Configuration
title: "Tiation Documentation Hub"
description: "Enterprise-grade centralized documentation for the Tiation ecosystem"
url: "https://tiation.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Plugin settings
relative_links:
  enabled: true
  collections: true

optional_front_matter:
  remove_originals: true

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: true

default_layout:
  markdown: default
  html: default

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/
  projects:
    output: true
    permalink: /:collection/:name/
  guides:
    output: true
    permalink: /:collection/:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "docs"
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "_guides"
      type: "guides"
    values:
      layout: "guide"

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Documentation"
    url: "/docs/"
  - title: "API Reference"
    url: "/docs/api-reference/"
  - title: "Architecture"
    url: "/docs/architecture/"
  - title: "Projects"
    url: "/projects/"
  - title: "GitHub"
    url: "https://github.com/tiation"

# SEO
author:
  name: "Tiation Team"
  email: "tiatheone@protonmail.com"
  twitter: "tiation"
  github: "tiation"

social:
  name: "Tiation"
  links:
    - "https://github.com/tiation"
    - "https://tiation.github.io"

# Enterprise features
enterprise:
  support_email: "tiatheone@protonmail.com"
  status_page: "https://status.tiation.ai"
  api_docs: "https://tiation.github.io/docs/api-reference/"
  architecture_docs: "https://tiation.github.io/docs/architecture/"
  deployment_docs: "https://tiation.github.io/docs/deployment/"

# Theme configuration
theme_config:
  primary_color: "#00FFFF"
  secondary_color: "#FF00FF"
  accent_color: "#007FFF"
  background_color: "#0A0A0A"
  text_color: "#FFFFFF"
  gradient_start: "#00FFFF"
  gradient_end: "#FF00FF"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md.backup
  - index_old.html
